name: Run build on Java 23

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build on Java 23
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 23
      - run: mvn -f pom.xml clean install

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:v1.0.0